### ISSUE TITLE
Bintray repo is outdated, possible to migrate elsewhere

### ISSUE THREAD

**Issue by vojkny** [vbmacher/cup-maven-plugin#15]
As the bintray repo has been suspended (as stated [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)), currently gradle url:

- https://plugins.gradle.org/m2/com/github/vbmacher/java-cup-runtime/11b-20160615/java-cup-runtime-11b-20160615.jar

is redirecting to:

- https://jcenter.bintray.com/com/github/vbmacher/java-cup-runtime/11b-20160615/java-cup-runtime-11b-20160615.jar

It would be great to migrate the repo to some maintained provider.

Thanks.

**Comment by vbmacher** [comment]
Hi @knyttl, you are using outdated version of cup-maven-plugin. Please update to version `11b-20160615-1`, or newest `11b-20160615-2` where just some maven dependencies were updated.
