### ISSUE TITLE
Invalid module name with Runtime

### ISSUE THREAD

**Issue by yoest** [vbmacher/cup-maven-plugin#17]
Hi,

We are having a problem with the use of this plugin, especially with the runtime, and it is impossible for us to understand why this is happening. When we use your plugin with maven, we get the following error:

```
Dependency: .../repository/com/github/vbmacher/java-cup-runtime/11b-20160615-2/java-cup-runtime-11b-20160615-2.jar
   - exception: Unable to derive module descriptor for .../repository/com/github/vbmacher/java-cup-runtime/11b-20160615-2/java-cup-runtime-11b-20160615-2.jar
   - cause: java.cup.runtime.11b.20160615: Invalid module name: '11b' is not a Java identifier
```

We would like to know if you know why this happens. We have only pasted the dependencies as indicated in the readme file.

Thank you for your time.

**Comment by vbmacher** [comment]
@yoest please try version `11b-20160615-3`
