### ISSUE TITLE
CUP Version

### ISSUE THREAD

**Issue by LeoWoerteler** [vbmacher/cup-maven-plugin#4]
While the maven artifact `nz.ac.waikato.cms.weka.thirdparty:java-cup-11b` suggests that it provides CUP version **11b**, it seems to be packaged improperly and actually contains version **11a**. This can e.g. be seen in the comments inserted into the generated parser class.

This also means that the newly introduced flag `-locations` cannot be used, which provides a richer API for source positions.

I contacted Dr. M. Hall of the Weka project regarding the wrong packaging, but he did not respond yet.

**Comment by vbmacher** [comment]
Hi, wow that's really... Thanks for the info, I didn't notice this. We can wait few days for his response, and if he does not reply, it will be maybe good to repackage my plug-in. I cannot find an alternative anyway..

**Comment by vbmacher** [comment]
I have repackaged Java CUP into two maven artifacts:
- `com.github.vbmacher:java-cup:11b`
- `com.github.vbmacher:java-cup-runtime:11b`

The original `cup-maven-plugin` now uses them. However, they are not yet uploaded to Maven Central. I will do it in next days.

**Comment by vbmacher** [comment]
OK, all the artifacts are uploaded to Sonatype Nexus; in few days they should be available to use. Can you please approve if they are fine and usable? Thanks in advance

**Comment by vbmacher** [comment]
Ok I have tried it in my project, and it seems it works. I am closing the issue.
