### ISSUE TITLE
Sources jars on maven central don't actualy contain any sources

### ISSUE THREAD

**Issue by kdvolder** [vbmacher/cup-maven-plugin#6]
Looks like sources jar are or have been incorrectly packaged. 

See here for example: the sources jar for 'java-cup-runtime' is here: https://repo1.maven.org/maven2/com/github/vbmacher/java-cup-runtime/11b/java-cup-runtime-11b-sources.jar

If you download that jar and open it you'll see that although it is supposed to be a 'sources' jar, it actually 
has no source files in it, just compiled .class files.

The 'java-cup' artifact also has the same problem as the 'java-cup-runtime' artifact.

**Comment by vbmacher** [comment]
Thanks for reporting! I hope I will find time this week for fixing it.

**Comment by vbmacher** [comment]
I have updated the sources and javadoc artifacts. Regarding repackaged artifacts, there is no official javadoc available so I just created README with link to the official documentation.

I also released the artifacts to Maven central, and changed version of the artifacts to correspond to the version used by original CUP.
