### ISSUE TITLE
Update to java-cup-11b-20160615

### ISSUE THREAD

**Issue by romildo** [vbmacher/cup-maven-plugin#7]
There is a new release of CUP. Please update the plugin to this release.

**Comment by vbmacher** [comment]
Hello, thanks for pointing out. I hope I get to it in a week or two.

**Comment by vbmacher** [comment]
I've deployed newest artifacts. We've got to wait for a day or two to Maven central updates database. I'll close the issue then.

However it seems they didn't update everything. For example, their site is still out of date. E.g., http://www2.cs.tum.edu/projects/cup/licence.php (1996-2015?), also it does not seem they've updated the documentation, nor the release notes (http://www2.cs.tum.edu/repos/cup/develop/changelog.txt - last version by now is 20151001).

Do you know what is new and how to use it? Or are you aware of any bugs to be hoping to be solved by the new version?

**Comment by romildo** [comment]
I don't know.

It is working for me.

**Comment by vbmacher** [comment]
Ok, never mind. Now the plugin is in Maven central, Im closing the issue.
